version: "3.8"

services:
  db:
    image: mysql
    restart: always
    container_name: syntro-db
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=syntro
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
